# EnemyData.gd
# Place this file at: res://resources/EnemyData.gd
# Generated by Bestiary Editor
extends Resource
class_name EnemyData

enum AIBehavior { HUNTER, RANDOM, GUARD }
enum Ailment { NONE, POISON, STUN, BURN, PARALYSIS }
#enum Loot_Table { EQUIP_1, EQUIP_2, EQUIP_3 }
enum Enemy_Type { NONE, UNDEAD, BEAST, HUMANOID, DEMON, DRAGON }

@export var enemy_name: String = ""
@export_file("*.tscn") var scene_path: String
@export var enemy_type: Enemy_Type
@export var hp: int = 100
@export var armor_class: int = 10
@export var dice_sides: int = 4
@export var dice_rolls: int = 1
@export var bonus_damage: int = 0
@export var is_ranged: bool = false
@export var ranged_tiles: int = 0
@export var status_effects: Array[String] = []
@export var skills: Array[Resource] = []
@export var accuracy: int = 0   # flat bonus to hit rolls
@export var critical_chance: int = 0
@export var magic_bonus: int = 0
@export var ailment: String = "none"
@export var attack_speed: int = 0
@export var initiative: int = -1
@export var cooldown: int = 0
@export var tier: int = 1
@export var xp: int = 0
@export var gold: int = 0
@export var ai_behavior: String = "Random"
@export var movement: int = 5
@export var sprite_texture: Texture2D
@export var loot_table: Array[LootManager.Loot_Table] = []
@export var quest_item_ids: Array[String] = []

@export var resist_fire: int = 0
@export var resist_physical: int = 0
@export var resist_cold: int = 0
@export var resist_earth: int = 0
@export var resist_electric: int = 0
@export var resist_light: int = 0
@export var resist_dark: int = 0

#@export var drops: Array[Resource] = []

@export var vision_range: int = 6
@export var vision_angle_deg: int = 120   # optional, for cone vision
@export var custom_scale: Vector3 = Vector3(1, 1, 1) # Default to no scaling
@export var custom_position:Vector3 = Vector3(0, 0, 0)
@export var custom_pixel_size: int = 0.01

var combat_buffs: Dictionary = {}
var status_metadata: Dictionary = {}

func get_ai_enum() -> AIBehavior:
	match ai_behavior:
		"Hunter": return AIBehavior.HUNTER
		"Guard": return AIBehavior.GUARD
		_: return AIBehavior.RANDOM

func get_ailment_enum() -> Ailment:
	match ailment:
		"poison": return Ailment.POISON
		"stun": return Ailment.STUN
		"burn": return Ailment.BURN
		"paralysis": return Ailment.PARALYSIS
		_: return Ailment.NONE

func get_resistance(element: String) -> int:
	match element:
		"fire": return resist_fire
		"physical": return resist_physical
		"cold": return resist_cold
		"earth": return resist_earth
		"electric": return resist_electric
		"light": return resist_light
		"dark": return resist_dark
	return 0
	
func get_accuracy() -> int:
	return accuracy + _get_combat_bonus("accuracy")

func get_armor_class() -> int:
	return armor_class + _get_combat_bonus("armor_class")

func get_bonus_damage() -> int:
	return bonus_damage + _get_combat_bonus("bonus_damage")

func get_magic_bonus() -> int:
	return magic_bonus + _get_combat_bonus("magic_bonus")

func apply_combat_buff(stat_name: String, value: int, duration_rounds: int = -1) -> void:
	var normalized := _normalize_combat_buff_key(stat_name)
	if normalized.is_empty() or value == 0:
		return

	var current_entry: Dictionary = _get_combat_buff_entry(normalized)
	var current_value := int(current_entry.get("value", 0))
	var new_entry := {
		"value": value,
		"remaining_rounds": duration_rounds
	}
	if value > 0:
		if value >= current_value:
			combat_buffs[normalized] = new_entry
	elif value < 0:
		if value <= current_value:
			combat_buffs[normalized] = new_entry

func clear_combat_buffs() -> void:
	combat_buffs.clear()

func tick_combat_buff_durations() -> void:
	for stat_name in combat_buffs.keys():
		var entry := _get_combat_buff_entry(stat_name)
		var remaining := int(entry.get("remaining_rounds", -1))
		if remaining < 0:
			continue
		remaining -= 1
		if remaining <= 0:
			combat_buffs.erase(stat_name)
		else:
			entry["remaining_rounds"] = remaining
			combat_buffs[stat_name] = entry

func _get_combat_bonus(stat_name: String) -> int:
	var normalized := _normalize_combat_buff_key(stat_name)
	if normalized.is_empty():
		return 0
	return int(_get_combat_buff_entry(normalized).get("value", 0))

func _get_combat_buff_entry(stat_name: String) -> Dictionary:
	var raw = combat_buffs.get(stat_name, {})
	if raw is Dictionary:
		return raw
	return {
		"value": int(raw),
		"remaining_rounds": -1
	}

func apply_status_effect(status_name: String, duration_rounds: int = -1, persists_after_combat: bool = true, save_dc: int = 0) -> void:
	var normalized := status_name.to_lower().strip_edges()
	if normalized.is_empty() or normalized == "none":
		return
	if not status_effects.has(normalized):
		status_effects.append(normalized)
	status_metadata[normalized] = {
		"remaining_rounds": duration_rounds,
		"persists_after_combat": persists_after_combat,
		"save_dc": save_dc
	}

func clear_status_effect(status_name: String) -> void:
	var normalized := status_name.to_lower().strip_edges()
	status_effects.erase(normalized)
	status_metadata.erase(normalized)

func clear_temporary_combat_statuses() -> void:
	for status_name in status_effects.duplicate():
		var metadata: Dictionary = status_metadata.get(status_name, {})
		if not bool(metadata.get("persists_after_combat", true)):
			clear_status_effect(status_name)

func tick_status_durations() -> void:
	for status_name in status_effects.duplicate():
		var metadata: Dictionary = status_metadata.get(status_name, {})
		var remaining := int(metadata.get("remaining_rounds", -1))
		if remaining < 0:
			continue
		remaining -= 1
		if remaining <= 0:
			clear_status_effect(status_name)
		else:
			metadata["remaining_rounds"] = remaining
			status_metadata[status_name] = metadata

func _normalize_combat_buff_key(stat_name: String) -> String:
	var key := stat_name.to_lower().strip_edges()
	match key:
		"accuracy":
			return "accuracy"
		"ac_bonus", "armor_class":
			return "armor_class"
		"bonus_damage", "damage":
			return "bonus_damage"
		"magic", "magic_bonus", "magic_amp":
			return "magic_bonus"
		_:
			return ""
