# EnemyData.gd
# Place this file at: res://resources/EnemyData.gd
# Generated by Bestiary Editor
extends Resource
class_name EnemyData

enum AIBehavior { HUNTER, RANDOM, GUARD }
enum Ailment { NONE, POISON, STUN, BURN, PARALYSIS }
#enum Loot_Table { EQUIP_1, EQUIP_2, EQUIP_3 }

@export var enemy_name: String = ""
@export_file("*.tscn") var scene_path: String
@export var hp: int = 100
@export var armor_class: int = 10
@export var dice_sides: int = 4
@export var dice_rolls: int = 1
@export var bonus_damage: int = 0
@export var is_ranged: bool = false
@export var ranged_tiles: int = 0
@export var status_effects: Array[String] = []
@export var accuracy: int = 0   # flat bonus to hit rolls
@export var critical_chance: int = 0
@export var magic_bonus: int = 0
@export var ailment: String = "none"
@export var attack_speed: int = 0
@export var initiative: int = -1
@export var cooldown: int = 0
@export var tier: int = 1
@export var xp: int = 0
@export var gold: int = 0
@export var ai_behavior: String = "Random"
@export var movement: int = 5
@export var sprite_texture: Texture2D
@export var loot_table: Array[LootManager.Loot_Table] = []
@export var quest_item_ids: Array[String] = []

@export var resist_fire: int = 0
@export var resist_physical: int = 0
@export var resist_cold: int = 0
@export var resist_earth: int = 0
@export var resist_electric: int = 0
@export var resist_light: int = 0
@export var resist_dark: int = 0

#@export var drops: Array[Resource] = []

@export var vision_range: int = 6
@export var vision_angle_deg: int = 120   # optional, for cone vision
@export var custom_scale: Vector3 = Vector3(1, 1, 1) # Default to no scaling
@export var custom_position:Vector3 = Vector3(0, 0, 0)
@export var custom_pixel_size: int = 0.01

func get_ai_enum() -> AIBehavior:
	match ai_behavior:
		"Hunter": return AIBehavior.HUNTER
		"Guard": return AIBehavior.GUARD
		_: return AIBehavior.RANDOM

func get_ailment_enum() -> Ailment:
	match ailment:
		"poison": return Ailment.POISON
		"stun": return Ailment.STUN
		"burn": return Ailment.BURN
		"paralysis": return Ailment.PARALYSIS
		_: return Ailment.NONE

func get_resistance(element: String) -> int:
	match element:
		"fire": return resist_fire
		"physical": return resist_physical
		"cold": return resist_cold
		"earth": return resist_earth
		"electric": return resist_electric
		"light": return resist_light
		"dark": return resist_dark
	return 0
	
func get_accuracy() -> int:
	return accuracy
